/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/b.glb 
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { fadeOnBeforeCompile } from '../utils/fadeMaterial';

export function B(props) {
  const { nodes, materials } = useGLTF('./models/b.glb');
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Plane001.geometry}>
        <meshStandardMaterial
          color={'white'}
          transparent
          envMapIntensity={1}
          onBeforeCompile={fadeOnBeforeCompile}
        />
      </mesh>
    </group>
  );
}

useGLTF.preload('./models/b.glb');
