/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/cloud/Earth.glb 
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

export function Earth(props) {
  const { nodes, materials } = useGLTF('./models/cloud/Earth.glb');
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes['Earth1-Mesh'].geometry}
        material={materials['02___Default']}
      />
      <mesh
        geometry={nodes['Earth1-Mesh_1'].geometry}
        material={materials.Mat}
      />
    </group>
  );
}

useGLTF.preload('./models/cloud/Earth.glb');
