/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/cloud/Jupiter.glb 
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

export function Jupiter(props) {
  const { nodes, materials } = useGLTF('./models/cloud/Jupiter.glb');
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Jupiter.geometry} material={materials.Mat} />
    </group>
  );
}

useGLTF.preload('./models/cloud/Jupiter.glb');
