/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/new-b.glb 
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { fullOpacityOnApproach } from '../utils/fadeMaterial';

export function B({ sceneOpacity, ...props }) {
  const { nodes, materials } = useGLTF('./models/new-b.glb');

  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Plane001.geometry}>
        <meshStandardMaterial
          transparent
          envMapIntensity={1}
          onBeforeCompile={fullOpacityOnApproach}
        />
      </mesh>
    </group>
  );
}

useGLTF.preload('./models/new-b.glb');
