/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/planet-1.glb 
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

export function Planets(props) {
  const { nodes, materials } = useGLTF('./models/planet-1.glb');
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.p4001.geometry}
        material={materials.texture}
        position={[2.277, 0.5, 1]}
      />
      <mesh
        geometry={nodes.p6001.geometry}
        material={materials.texture}
        position={[1.217, 2.133, 2]}
      />
      <mesh
        geometry={nodes.p5001.geometry}
        material={materials.texture}
        position={[-3.699, 2.272, 2]}
      />
      <mesh
        geometry={nodes.p13001.geometry}
        material={materials.texture}
        position={[-2.255, 1.365, 10]}
      />
      <mesh
        geometry={nodes.p8001.geometry}
        material={materials.texture}
        position={[-6.271, 0.543, 1.91]}
      />
      <mesh
        geometry={nodes.p12001.geometry}
        material={materials.texture}
        position={[-3, 2.842, 1.905]}
      />
      <mesh
        geometry={nodes.p9001.geometry}
        material={materials.texture}
        position={[3, 0.713, 1.787]}
      />
      <mesh
        geometry={nodes.p10001.geometry}
        material={materials.texture}
        position={[-3, 1.321, 1.897]}
      />
      <group position={[-3, 0.839, 10]}>
        <mesh
          geometry={nodes.Circle001.geometry}
          material={materials.texture}
        />
        <mesh
          geometry={nodes.Circle001_1.geometry}
          material={materials.Material}
        />
      </group>
      <mesh
        geometry={nodes.p2001.geometry}
        material={materials.texture}
        position={[-3, 1, 1.918]}
      />
      <mesh
        geometry={nodes.p3001.geometry}
        material={materials.texture}
        position={[3, 2, 1.857]}
      />
    </group>
  );
}

useGLTF.preload('./models/planet-1.glb');
