/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/planet.glb 
*/

import React, { useMemo, useRef } from 'react';
import { useGLTF } from '@react-three/drei';

import { fullOpacityOnApproach } from '../utils/fadeMaterial';

export function Planet(props) {
  const { nodes, materials } = useGLTF('./models/planet.glb');
  useMemo(() => {
    for (const key in materials) {
      if (materials.hasOwnProperty(key)) {
        const material = materials[key];
        material.transparent = true;
        material.onBeforeCompile = fullOpacityOnApproach;
      }
    }
  }, [materials]);

  return (
    <group {...props} dispose={null}>
      <mesh
        position={[-1, -8, -6]}
        geometry={nodes.gr.geometry}
        material={materials.pl11}
        scale={20}
      />

      <group position={[-10, -5, -50]} scale={5} rotation={[-2.6, 0, 0.4]}>
        <mesh
          geometry={nodes.Circle003.geometry}
          material={materials['Material.001']}
        />
        <mesh geometry={nodes.Circle003_1.geometry} material={materials.pl9} />
      </group>
      <mesh
        position={[20, 16, -150]}
        geometry={nodes.wh2.geometry}
        material={materials.pl4}
        scale={20}
      />

      <mesh
        position={[20, -10, -250]}
        geometry={nodes.br.geometry}
        material={materials.pl1}
        rotation={[-3.105, 0.145, 0.484]}
        scale={30}
      />
      <mesh
        position={[-22, 14, -300]}
        geometry={nodes.wh.geometry}
        material={materials.pl6}
        scale={10}
      />
      <group
        rotation={[0.141, 0.143, 0.357]}
        scale={20}
        position={[-20, 20, -200]}
      >
        <mesh
          geometry={nodes.Circle003.geometry}
          material={materials['Material.001']}
        />
        <mesh geometry={nodes.Circle003_1.geometry} material={materials.pl9} />
      </group>
      <group scale={20} position={[16, 16, -400]}>
        <mesh geometry={nodes.Sphere008.geometry} material={materials.pl7} />
        <mesh
          geometry={nodes.Sphere008_1.geometry}
          material={materials['Material.003']}
        />
      </group>
      <mesh
        position={[-20, -8, -500]}
        geometry={nodes.sb.geometry}
        material={materials.pl3}
        scale={16}
      />
      <mesh
        position={[20, -10, -550]}
        geometry={nodes.ye.geometry}
        material={materials.pl10}
        scale={20}
      />
      <mesh
        position={[-24, 20, -600]}
        geometry={nodes.bl.geometry}
        material={materials.pl2}
        rotation={[-3.024, 0.138, 0.622]}
        scale={30}
      />
      <mesh
        position={[-4, -16, -700]}
        geometry={nodes.ye.geometry}
        material={materials.pl10}
        scale={30}
      />
      <group scale={20} position={[-40, 16, -750]}>
        <mesh geometry={nodes.Sphere008.geometry} material={materials.pl7} />
        <mesh
          geometry={nodes.Sphere008_1.geometry}
          material={materials['Material.003']}
        />
      </group>
      <mesh
        position={[20, 20, -800]}
        geometry={nodes.wh2.geometry}
        material={materials.pl4}
        scale={30}
      />

      <group position={[-24, -24, -900]} scale={20}>
        <mesh
          geometry={nodes.Circle005.geometry}
          material={materials.Material}
        />
        <mesh geometry={nodes.Circle005_1.geometry} material={materials.pl1} />
      </group>
      <group
        rotation={[0.141, 0.143, 0.357]}
        scale={20}
        position={[-20, 20, -950]}
      >
        <mesh
          geometry={nodes.Circle003.geometry}
          material={materials['Material.001']}
        />
        <mesh geometry={nodes.Circle003_1.geometry} material={materials.pl9} />
      </group>
      <mesh
        position={[30, 10, -1000]}
        geometry={nodes.gr.geometry}
        material={materials.pl11}
        scale={30}
      />
      <mesh
        position={[10, -20, -1100]}
        geometry={nodes.ye.geometry}
        material={materials.pl10}
        scale={20}
      />
      <group scale={30} position={[-30, 20, -1100]}>
        <mesh
          geometry={nodes.Circle002.geometry}
          material={materials['Material.002']}
        />
        <mesh geometry={nodes.Circle002_1.geometry} material={materials.pl8} />
      </group>
    </group>
  );
}

useGLTF.preload('./models/planet.glb');
