/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/cloud/Planets.glb 
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

export function Planets(props) {
  const { nodes, materials } = useGLTF('./models/cloud/Planets.glb');
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes['Node-Mesh'].geometry}
        material={materials.PlanetsB_mat}
      />
      <mesh
        geometry={nodes['Node-Mesh_1'].geometry}
        material={materials.PlanetsA_mat}
      />
    </group>
  );
}

useGLTF.preload('./models/cloud/Planets.glb');
