/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/rainbow.glb 
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

export function Rainbow(props) {
  const { nodes, materials } = useGLTF('./models/rainbow.glb');
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.rainbow.geometry} material={materials.None} />
    </group>
  );
}

useGLTF.preload('./models/rainbow.glb');
