/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/real-building.glb 
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

export function RealBuilding(props) {
  const { nodes, materials } = useGLTF('./models/real-building.glb');
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Highrise_1.geometry}
        material={materials['default']}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.026}
      />
      <mesh
        geometry={nodes.Highrise_10.geometry}
        material={materials['default']}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.026}
      />
      <mesh
        geometry={nodes.Highrise_11.geometry}
        material={materials['default']}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.026}
      />
      <mesh
        geometry={nodes.Highrise_12.geometry}
        material={materials['default']}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.026}
      />
      <mesh
        geometry={nodes.highrise_13.geometry}
        material={materials['default']}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.026}
      />
      <mesh
        geometry={nodes.Highrise_14.geometry}
        material={materials['default']}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.026}
      />
      <mesh
        geometry={nodes.Highrise_15.geometry}
        material={materials['default']}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.026}
      />
      <mesh
        geometry={nodes.Highrise_16.geometry}
        material={materials['default']}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.026}
      />
      <mesh
        geometry={nodes.Highrise_17.geometry}
        material={materials['default']}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.026}
      />
      <mesh
        geometry={nodes.Highrise_18.geometry}
        material={materials['default']}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.026}
      />
      <mesh
        geometry={nodes.Highrise_19.geometry}
        material={nodes.Highrise_19.material}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.026}
      />
      <mesh
        geometry={nodes.Highrise_2.geometry}
        material={materials['default']}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.026}
      />
      <mesh
        geometry={nodes.Highrise_3.geometry}
        material={materials['default']}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.026}
      />
      <mesh
        geometry={nodes.Highrise_4.geometry}
        material={materials['default']}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.026}
      />
      <mesh
        geometry={nodes.Highrise_5.geometry}
        material={materials['default']}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.026}
      />
      <mesh
        geometry={nodes.Highrise_6.geometry}
        material={materials['default']}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.026}
      />
      <mesh
        geometry={nodes.Highrise_7.geometry}
        material={materials['default']}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.026}
      />
      <mesh
        geometry={nodes.Highrise_8.geometry}
        material={materials['default']}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.026}
      />
      <mesh
        geometry={nodes.Highrise_9.geometry}
        material={materials['default']}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.026}
      />
    </group>
  );
}

useGLTF.preload('./models/real-building.glb');
