/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 su1.glb 
*/

import React, { useRef, useEffect } from 'react';
import { useGLTF, useAnimations } from '@react-three/drei';

export function Su1({ curvePoints, props }) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF('./su1.glb');
  const { actions } = useAnimations(animations, group);
  useEffect(() => {
    if (actions?.['Scene']?.play() !== undefined) {
      actions?.['Scene'].play();
    }
  }, [actions]);
  return (
    <group
      ref={group}
      {...props}
      dispose={null}
      scale={2}
      position={[curvePoints.x + 4, curvePoints.y - 0.5, curvePoints.z]}
    >
      <group name="Scene">
        <mesh
          name="Sphere001"
          geometry={nodes.Sphere001.geometry}
          material={materials.pl8}
          rotation={[-0.032, 0, -0.273]}
        />
        <group
          name="Cube001"
          position={[3.391, -0.922, 0.762]}
          rotation={[-0.091, -0.197, -0.278]}
          scale={0.477}
        >
          <mesh
            name="Cube001_1"
            geometry={nodes.Cube001_1.geometry}
            material={materials['Material.006']}
            morphTargetDictionary={nodes['Cube001_1'].morphTargetDictionary}
            morphTargetInfluences={nodes['Cube001_1'].morphTargetInfluences}
          />
          <mesh
            name="Cube001_2"
            geometry={nodes.Cube001_2.geometry}
            material={materials['Material.007']}
            morphTargetDictionary={nodes['Cube001_2'].morphTargetDictionary}
            morphTargetInfluences={nodes['Cube001_2'].morphTargetInfluences}
          />
          <mesh
            name="Cube001_3"
            geometry={nodes.Cube001_3.geometry}
            material={materials['Material.008']}
            morphTargetDictionary={nodes['Cube001_3'].morphTargetDictionary}
            morphTargetInfluences={nodes['Cube001_3'].morphTargetInfluences}
          />
          <mesh
            name="Cube001_4"
            geometry={nodes.Cube001_4.geometry}
            material={materials['Material.009']}
            morphTargetDictionary={nodes['Cube001_4'].morphTargetDictionary}
            morphTargetInfluences={nodes['Cube001_4'].morphTargetInfluences}
          />
        </group>
        <mesh
          name="Plane001"
          geometry={nodes.Plane001.geometry}
          material={materials['Material.005']}
          position={[0.335, 0.304, 0.031]}
          rotation={[2.976, -0.58, -2.756]}
          morphTargetDictionary={nodes['Plane001'].morphTargetDictionary}
          morphTargetInfluences={nodes['Plane001'].morphTargetInfluences}
        />
      </group>
    </group>
  );
}

useGLTF.preload('./su1.glb');
