/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 su2.glb su3.glb 
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/su2.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh name="Sphere" geometry={nodes.Sphere.geometry} material={materials.pl11} rotation={[0, 0, -0.256]}>
          <mesh name="Cube001" geometry={nodes.Cube001.geometry} material={materials['Material.001']} position={[-1.346, 0.048, 0.409]} rotation={[-2.884, -0.253, 3.09]} scale={1.015}>
            <mesh name="Plane" geometry={nodes.Plane.geometry} material={nodes.Plane.material} position={[0.285, 0.044, 0.008]} rotation={[0.046, 0.586, 0.291]} scale={[0.985, 0.858, 0.985]} />
            <mesh name="Plane001" geometry={nodes.Plane001.geometry} material={nodes.Plane001.material} position={[-0.29, 0.04, -0.007]} rotation={[-3.103, -0.597, -2.807]} scale={[0.985, 0.858, 0.985]} />
          </mesh>
          <mesh name="Cylinder003" geometry={nodes.Cylinder003.geometry} material={materials['Material.003']} position={[0.84, 0.216, -1.106]} rotation={[-2.259, 0.498, 0.466]} scale={1.674}>
            <mesh name="Plane002" geometry={nodes.Plane002.geometry} material={materials['Material.003']} position={[-0.018, -0.027, 0.026]} rotation={[1.579, -0.995, 0.136]} scale={[0.597, 0.52, 0.597]} />
            <mesh name="Plane003" geometry={nodes.Plane003.geometry} material={materials['Material.003']} position={[-0.022, 0.011, 0.022]} rotation={[1.579, -0.995, 0.136]} scale={[0.597, 0.52, 0.597]} />
          </mesh>
          <group name="Empty" position={[1.221, -0.077, 0.925]} rotation={[-0.157, -0.435, -0.34]} scale={1.199}>
            <mesh name="Cylinder" geometry={nodes.Cylinder.geometry} material={materials['Material.003']} position={[-0.078, 0, 0.139]} />
            <mesh name="Cylinder001" geometry={nodes.Cylinder001.geometry} material={materials['Material.003']} position={[0.155, 0, -0.003]}>
              <mesh name="Plane005" geometry={nodes.Plane005.geometry} material={materials['Material.003']} position={[-0.212, 0.256, 0.115]} rotation={[-2.512, -0.335, -1.178]} scale={[0.501, 0.436, 0.501]} />
              <mesh name="Plane006" geometry={nodes.Plane006.geometry} material={materials['Material.003']} position={[0.015, 0.14, -0.021]} rotation={[-2.512, -0.335, -1.178]} scale={[0.501, 0.436, 0.501]} />
            </mesh>
            <mesh name="Cylinder002" geometry={nodes.Cylinder002.geometry} material={materials['Material.003']} position={[-0.078, 0, -0.136]}>
              <mesh name="Plane004_1" geometry={nodes.Plane004_1.geometry} material={materials['Material.003']} position={[0.014, 0.432, -0.023]} rotation={[-2.512, -0.335, -1.178]} scale={[0.501, 0.436, 0.501]} />
            </mesh>
          </group>
        </mesh>
      </group>
    </group>
  )
}

useGLTF.preload('/su2.glb')
