/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 su3.glb 
*/

import React, { useRef, useEffect, useMemo } from 'react';
import { useGLTF, useAnimations } from '@react-three/drei';
import { fullOpacityOnApproach } from '../utils/fadeMaterial';

export function Su3({ props, curvePoints }) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF('./su3.glb');
  const { actions } = useAnimations(animations, group);
  useMemo(() => {
    for (const key in materials) {
      if (materials.hasOwnProperty(key)) {
        const material = materials[key];
        material.transparent = true;
        material.onBeforeCompile = fullOpacityOnApproach;
      }
    }
  }, [materials]);
  useEffect(() => {
    if (actions?.['Scene']?.play() !== undefined) {
      actions?.['Scene'].play();
    }
  }, [actions]);

  return (
    <group
      ref={group}
      {...props}
      dispose={null}
      scale={2}
      position={[curvePoints.x + 3, curvePoints.y, curvePoints.z]}
    >
      <group name="Scene">
        <group name="Empty003" position={[0, -0.588, 0]} scale={0.889}>
          <group
            name="Empty001"
            rotation={[Math.PI, -0.089, Math.PI]}
            scale={1.078}
          >
            <group
              name="Empty"
              position={[0.039, 0.502, 1.363]}
              rotation={[2.403, -1.507, 2.368]}
              scale={1.208}
            >
              <group name="01_rig" position={[-0.433, -0.003, -1.511]}>
                <primitive object={nodes.root} />
                <skinnedMesh
                  name="01"
                  geometry={nodes['01'].geometry}
                  material={materials.skin}
                  skeleton={nodes['01'].skeleton}
                />
                <skinnedMesh
                  name="01001"
                  geometry={nodes['01001'].geometry}
                  material={materials['Material.002']}
                  skeleton={nodes['01001'].skeleton}
                />
              </group>
            </group>
          </group>
          <group
            name="Empty002"
            rotation={[Math.PI, -0.457, Math.PI]}
            scale={1.188}
          >
            <group
              name="01_rig001"
              position={[-1.639, 0.37, 1.512]}
              rotation={[-0.739, 1.507, 0.774]}
              scale={1.096}
            >
              <primitive object={nodes.root_1} />
              <skinnedMesh
                name="01002"
                geometry={nodes['01002'].geometry}
                material={materials.skin}
                skeleton={nodes['01002'].skeleton}
              />
              <skinnedMesh
                name="01003"
                geometry={nodes['01003'].geometry}
                material={materials['Material.002']}
                skeleton={nodes['01003'].skeleton}
              />
            </group>
          </group>
        </group>
        <mesh
          name="Sphere"
          geometry={nodes.Sphere.geometry}
          material={materials.pl6}
          rotation={[0.495, -0.187, 0.361]}
        />
        <mesh
          name="Cylinder"
          geometry={nodes.Cylinder.geometry}
          material={materials.Material}
          position={[0.041, -0.136, 1.291]}
          rotation={[0.973, -0.276, 0.147]}
          scale={0}
        >
          <group
            name="Cylinder001"
            position={[0.215, -1.5, 7.25]}
            rotation={[-0.682, -0.336, -2.549]}
            scale={[-1.784, -0.114, -5.959]}
          >
            <mesh
              name="Cylinder003"
              geometry={nodes.Cylinder003.geometry}
              material={materials['Material.010']}
            />
            <mesh
              name="Cylinder003_1"
              geometry={nodes.Cylinder003_1.geometry}
              material={materials['Material.011']}
            />
            <mesh
              name="Cylinder003_2"
              geometry={nodes.Cylinder003_2.geometry}
              material={materials['Material.012']}
            />
          </group>
          <mesh
            name="Plane"
            geometry={nodes.Plane.geometry}
            material={nodes.Plane.material}
            position={[0.215, 60, 7.125]}
            rotation={[-0.738, -0.123, -2.369]}
            scale={[-3.987, -9.97, -4.307]}
          />
        </mesh>
      </group>
    </group>
  );
}

useGLTF.preload('./su3.glb');
