/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 su4.glb 
*/

import React, { useRef, useEffect, useMemo } from 'react';
import { useGLTF, useAnimations } from '@react-three/drei';
import { fullOpacityOnApproach } from '../utils/fadeMaterial';

export function Su4({ props, curvePoints }) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF('./su4.glb');
  const { actions } = useAnimations(animations, group);
  useMemo(() => {
    for (const key in materials) {
      if (materials.hasOwnProperty(key)) {
        const material = materials[key];
        material.transparent = true;
        material.onBeforeCompile = fullOpacityOnApproach;
      }
    }
  }, [materials]);
  useEffect(() => {
    if (actions?.['Scene']?.play() !== undefined) {
      actions?.['Scene'].play();
    }
  }, [actions]);
  return (
    <group
      ref={group}
      {...props}
      dispose={null}
      scale={3}
      position={[curvePoints.x - 3, curvePoints.y - 1, curvePoints.z]}
    >
      <group name="Scene">
        <group name="Empty" position={[0.026, -0.181, 0.53]} scale={0.723}>
          <mesh
            name="Dummy_37"
            geometry={nodes.Dummy_37.geometry}
            material={materials['Material.011']}
            position={[0.211, 0.454, 0.058]}
            scale={0}
          >
            <mesh
              name="Base_haircut_20"
              geometry={nodes.Base_haircut_20.geometry}
              material={materials['20']}
              position={[0, 0, -0.001]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={0.012}
            />
            <mesh
              name="Base_haircut_21002"
              geometry={nodes.Base_haircut_21002.geometry}
              material={materials['21']}
              position={[0, 0, -3.53]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={355.712}
            />
            <mesh
              name="Sphere002"
              geometry={nodes.Sphere002.geometry}
              material={materials['Material.001']}
              position={[0, -15.292, -10.673]}
              scale={[38.633, 24.918, 24.953]}
            >
              <mesh
                name="Cylinder001"
                geometry={nodes.Cylinder001.geometry}
                material={nodes.Cylinder001.material}
                position={[0, 0, 0.069]}
                scale={[6.58, 10.201, 10.187]}
              />
              <group name="Sphere005" scale={[1.078, 1.007, 0.893]}>
                <mesh
                  name="Sphere005_1"
                  geometry={nodes.Sphere005_1.geometry}
                  material={materials['Material.001']}
                />
                <mesh
                  name="Sphere005_2"
                  geometry={nodes.Sphere005_2.geometry}
                  material={materials['Material.005']}
                />
              </group>
            </mesh>
          </mesh>
          <mesh
            name="Dummy_37001"
            geometry={nodes.Dummy_37001.geometry}
            material={materials['Material.012']}
            position={[-0.242, 0.405, 0.048]}
            scale={0}
          >
            <group name="Base_Haircut_38" position={[-2, 0, 0]} scale={0}>
              <mesh
                name="Cube051"
                geometry={nodes.Cube051.geometry}
                material={materials.Ribbon}
              />
              <mesh
                name="Cube051_1"
                geometry={nodes.Cube051_1.geometry}
                material={materials.Anna_hairStrand}
              />
            </group>
            <mesh
              name="Base_haircut_21003"
              geometry={nodes.Base_haircut_21003.geometry}
              material={materials['21']}
              position={[-1, 0, -4]}
              scale={0}
            />
            <mesh
              name="Sphere001"
              geometry={nodes.Sphere001.geometry}
              material={materials['Material.001']}
              position={[-2, 0, 0]}
              scale={0}
            >
              <mesh
                name="Cylinder003"
                geometry={nodes.Cylinder003.geometry}
                material={nodes.Cylinder003.material}
                position={[-2, 0, 0]}
                scale={0}
              />
              <group name="Sphere006" position={[-1, 0, -4]} scale={0}>
                <mesh
                  name="Sphere006_1"
                  geometry={nodes.Sphere006_1.geometry}
                  material={materials['Material.001']}
                />
                <mesh
                  name="Sphere006_2"
                  geometry={nodes.Sphere006_2.geometry}
                  material={materials['Material.009']}
                />
              </group>
              <group name="Sphere007" position={[-1, 0, -4]} scale={0}>
                <mesh
                  name="Sphere007_1"
                  geometry={nodes.Sphere007_1.geometry}
                  material={materials['Material.001']}
                />
                <mesh
                  name="Sphere007_2"
                  geometry={nodes.Sphere007_2.geometry}
                  material={materials['Material.004']}
                />
              </group>
            </mesh>
          </mesh>
          <mesh
            name="Gear"
            geometry={nodes.Gear.geometry}
            material={materials['Material.008']}
            position={[0.004, 0.345, 0.256]}
            scale={0}
          />
          <mesh
            name="Gear001"
            geometry={nodes.Gear001.geometry}
            material={materials['Material.008']}
            position={[0.256, 0.372, 0.026]}
            scale={0}
          />
          <mesh
            name="Gear002"
            geometry={nodes.Gear002.geometry}
            material={materials['Material.008']}
            position={[-0.244, 0.38, 0.018]}
            scale={0}
          />
          <mesh
            name="Sphere"
            geometry={nodes.Sphere.geometry}
            material={materials['Material.001']}
            position={[0.004, 0.436, 0.256]}
            scale={0}
          >
            <mesh
              name="Cylinder002"
              geometry={nodes.Cylinder002.geometry}
              material={nodes.Cylinder002.material}
              position={[0.25, 1, 8]}
              scale={0}
            />
            <mesh
              name="Dummy_40"
              geometry={nodes.Dummy_40.geometry}
              material={materials['Material.002']}
              position={[0.25, 1, 8]}
              scale={0}
            >
              <mesh
                name="Base_haircut_21"
                geometry={nodes.Base_haircut_21.geometry}
                material={materials['21']}
                position={[0.25, 1, 8]}
                scale={0}
              />
              <mesh
                name="Base_haircut_21001"
                geometry={nodes.Base_haircut_21001.geometry}
                material={materials['21']}
                position={[0.25, 1, 8]}
                scale={0}
              />
              <mesh
                name="Base_haircut_21004"
                geometry={nodes.Base_haircut_21004.geometry}
                material={materials['21']}
                position={[0.25, 1, 8]}
                scale={0}
              />
            </mesh>
          </mesh>
          <group name="Sphere004" position={[0.004, 0.436, 0.256]} scale={0}>
            <mesh
              name="Sphere004_1"
              geometry={nodes.Sphere004_1.geometry}
              material={materials['Material.001']}
            />
            <mesh
              name="Sphere004_2"
              geometry={nodes.Sphere004_2.geometry}
              material={materials['Material.003']}
            />
          </group>
        </group>
        <mesh
          name="Sphere003"
          geometry={nodes.Sphere003.geometry}
          material={materials.pl9}
          rotation={[Math.PI, -0.026, Math.PI]}
        >
          <mesh
            name="Cylinder"
            geometry={nodes.Cylinder.geometry}
            material={materials['Material.007']}
          />
        </mesh>
      </group>
    </group>
  );
}

useGLTF.preload('./su4.glb');
