/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 su5.glb 
*/

import React, { useRef, useEffect } from 'react';
import { useGLTF, useAnimations } from '@react-three/drei';

export function Su5({ props, curvePoints }) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF('./su5.glb');
  const { actions } = useAnimations(animations, group);
  useEffect(() => {
    if (actions?.['Scene']?.play() !== undefined) {
      actions?.['Scene'].play();
    }
  }, [actions]);
  return (
    <group
      ref={group}
      {...props}
      dispose={null}
      scale={1.5}
      position={[curvePoints.x + 6, curvePoints.y, curvePoints.z]}
    >
      <group name="Scene">
        <group name="BezierCircle" />
        <group name="Empty" rotation={[0.17, 0.076, 0.158]}>
          <mesh
            name="Sphere"
            geometry={nodes.Sphere.geometry}
            material={materials.pl7}
          >
            <mesh
              name="Cube001"
              geometry={nodes.Cube001.geometry}
              material={materials['Material.005']}
              position={[-0.957, 0.164, -0.937]}
              scale={0.581}
            />
            <group
              name="Cube002"
              position={[0.555, 0.23, 1.2]}
              rotation={[-3.068, 1.093, 3.07]}
              scale={0.495}
            >
              <mesh
                name="Cube002_1"
                geometry={nodes.Cube002_1.geometry}
                material={materials['Material.004']}
              />
              <mesh
                name="Cube002_2"
                geometry={nodes.Cube002_2.geometry}
                material={materials['Material.009']}
              />
              <mesh
                name="Cube002_3"
                geometry={nodes.Cube002_3.geometry}
                material={materials['Material.001']}
              />
              <mesh
                name="Cube002_4"
                geometry={nodes.Cube002_4.geometry}
                material={materials['Material.002']}
              />
              <mesh
                name="Cube002_5"
                geometry={nodes.Cube002_5.geometry}
                material={materials['Material.010']}
              />
              <mesh
                name="Cube002_6"
                geometry={nodes.Cube002_6.geometry}
                material={materials['Material.003']}
              />
            </group>
            <group
              name="Cube003"
              position={[1.311, 0.227, -0.083]}
              rotation={[-3.135, -0.168, 3.109]}
              scale={0.495}
            >
              <mesh
                name="Cube003_1"
                geometry={nodes.Cube003_1.geometry}
                material={materials['Material.004']}
              />
              <mesh
                name="Cube003_2"
                geometry={nodes.Cube003_2.geometry}
                material={materials['Material.009']}
              />
              <mesh
                name="Cube003_3"
                geometry={nodes.Cube003_3.geometry}
                material={materials['Material.001']}
              />
              <mesh
                name="Cube003_4"
                geometry={nodes.Cube003_4.geometry}
                material={materials['Material.002']}
              />
              <mesh
                name="Cube003_5"
                geometry={nodes.Cube003_5.geometry}
                material={materials['Material.010']}
              />
              <mesh
                name="Cube003_6"
                geometry={nodes.Cube003_6.geometry}
                material={materials['Material.003']}
              />
            </group>
            <mesh
              name="Cube004"
              geometry={nodes.Cube004.geometry}
              material={materials['Material.005']}
              position={[-1.165, 0.189, 0.669]}
              rotation={[0, 1.062, 0]}
              scale={0.745}
            />
            <mesh
              name="Cube005"
              geometry={nodes.Cube005.geometry}
              material={materials['Material.005']}
              position={[0.896, 0.164, -1]}
              rotation={[0, -1.519, 0]}
              scale={0.581}
            />
            <group
              name="Cube006"
              position={[-1.308, 0.25, -0.176]}
              rotation={[0.015, -0.092, 0.033]}
              scale={0.495}
            >
              <mesh
                name="Cube004_1"
                geometry={nodes.Cube004_1.geometry}
                material={materials['Material.004']}
              />
              <mesh
                name="Cube004_2"
                geometry={nodes.Cube004_2.geometry}
                material={materials['Material.009']}
              />
              <mesh
                name="Cube004_3"
                geometry={nodes.Cube004_3.geometry}
                material={materials['Material.001']}
              />
              <mesh
                name="Cube004_4"
                geometry={nodes.Cube004_4.geometry}
                material={materials['Material.002']}
              />
              <mesh
                name="Cube004_5"
                geometry={nodes.Cube004_5.geometry}
                material={materials['Material.010']}
              />
              <mesh
                name="Cube004_6"
                geometry={nodes.Cube004_6.geometry}
                material={materials['Material.003']}
              />
            </group>
            <mesh
              name="Cube007"
              geometry={nodes.Cube007.geometry}
              material={materials['Material.005']}
              position={[-0.011, 0.197, 1.356]}
              rotation={[0, 1.443, 0]}
              scale={0.775}
            />
            <mesh
              name="Cube009"
              geometry={nodes.Cube009.geometry}
              material={materials['Material.005']}
              position={[1.13, 0.164, 0.743]}
              rotation={[Math.PI, -0.2, Math.PI]}
              scale={0.581}
            />
            <mesh
              name="Cube011"
              geometry={nodes.Cube011.geometry}
              material={materials['Material.005']}
              position={[-0.033, 0.083, -1.329]}
              rotation={[0, -0.847, 0]}
              scale={0.583}
            />
            <mesh
              name="Cube012"
              geometry={nodes.Cube012.geometry}
              material={materials['Material.005']}
              position={[-0.011, 0.287, 1.356]}
              rotation={[0, 1.008, 0]}
              scale={0.471}
            />
            <mesh
              name="Cube013"
              geometry={nodes.Cube013.geometry}
              material={materials['Material.005']}
              position={[1.097, 0.313, 0.775]}
              rotation={[-Math.PI, 0.199, -Math.PI]}
              scale={0.28}
            />
            <mesh
              name="Cube014"
              geometry={nodes.Cube014.geometry}
              material={materials['Material.005']}
              position={[-0.964, 0.324, -0.944]}
              rotation={[0, -0.333, 0]}
              scale={0.37}
            />
          </mesh>
          <group name="Cube" position={[0.003, 0.012, -0.007]} scale={0.934}>
            <mesh
              name="Cube_1"
              geometry={nodes.Cube_1.geometry}
              material={materials['Material.008']}
            />
            <mesh
              name="Cube_2"
              geometry={nodes.Cube_2.geometry}
              material={materials.Material}
            />
          </group>
          <mesh
            name="Cylinder"
            geometry={nodes.Cylinder.geometry}
            material={materials['Material.006']}
            position={[0.003, 0.012, -0.007]}
            scale={0.941}
          />
          <mesh
            name="Cylinder001"
            geometry={nodes.Cylinder001.geometry}
            material={materials['Material.007']}
            position={[0.003, 0.012, -0.007]}
            scale={0.941}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload('./su5.glb');
