/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 su6.glb 
*/

import React, { useRef, useEffect, useMemo } from 'react';
import { useGLTF, useAnimations } from '@react-three/drei';
import { fullOpacityOnApproach } from '../utils/fadeMaterial';

export function Su6({ props, curvePoints }) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF('./su6.glb');
  const { actions } = useAnimations(animations, group);
  useMemo(() => {
    for (const key in materials) {
      if (materials.hasOwnProperty(key)) {
        const material = materials[key];
        material.transparent = true;
        material.onBeforeCompile = fullOpacityOnApproach;
      }
    }
  }, [materials]);
  useEffect(() => {
    if (actions?.['Scene']?.play() !== undefined) {
      actions?.['Scene'].play();
    }
  }, [actions]);
  return (
    <group
      ref={group}
      {...props}
      dispose={null}
      scale={3}
      position={[curvePoints.x - 4, curvePoints.y, curvePoints.z - 5]}
    >
      <group name="Scene">
        <group name="Empty" rotation={[-0.14, -0.028, -0.332]}>
          <mesh
            name="Superhero_by_AlexLashko_V2"
            geometry={nodes.Superhero_by_AlexLashko_V2.geometry}
            material={materials.lambert1}
            position={[-0.494, 0.083, 1.548]}
            rotation={[-0.201, 1.479, -0.011]}
            scale={4.492}
          >
            <mesh
              name="Sphere001"
              geometry={nodes.Sphere001.geometry}
              material={materials['Material.005']}
              position={[-0.079, 0.009, -0.023]}
              rotation={[0.095, 0.027, 0.392]}
              scale={0.048}
            >
              <mesh
                name="Sphere002"
                geometry={nodes.Sphere002.geometry}
                material={materials['Material.007']}
              />
              <mesh
                name="Sphere003"
                geometry={nodes.Sphere003.geometry}
                material={materials['Material.006']}
                scale={0}
              >
                <mesh
                  name="Plane"
                  geometry={nodes.Plane.geometry}
                  material={materials['Material.006']}
                  position={[0, 0, 16]}
                  scale={0}
                />
                <mesh
                  name="Plane001"
                  geometry={nodes.Plane001.geometry}
                  material={materials['Material.006']}
                  position={[0, 0, 16]}
                  scale={0}
                />
                <mesh
                  name="Plane002"
                  geometry={nodes.Plane002.geometry}
                  material={materials['Material.006']}
                  position={[0, 0, 16]}
                  scale={0}
                />
                <mesh
                  name="Plane003"
                  geometry={nodes.Plane003.geometry}
                  material={materials['Material.006']}
                  position={[0, 0, 16]}
                  scale={0}
                />
                <mesh
                  name="Plane004"
                  geometry={nodes.Plane004.geometry}
                  material={materials['Material.006']}
                  position={[0, 0, 16]}
                  scale={0}
                />
                <mesh
                  name="Plane005"
                  geometry={nodes.Plane005.geometry}
                  material={materials['Material.006']}
                  position={[0, 0, 16]}
                  scale={0}
                />
              </mesh>
            </mesh>
          </mesh>
        </group>
        <mesh
          name="Sphere"
          geometry={nodes.Sphere.geometry}
          material={materials.pl2}
          rotation={[3.001, 0.028, -2.809]}
        />
      </group>
    </group>
  );
}

useGLTF.preload('./su6.glb');
