/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/suni.glb 
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { useFrame } from '@react-three/fiber';

const LEG_SPEED = 6;

export function Suni(props) {
  const { nodes, materials } = useGLTF('./models/suni.glb');

  const helix = useRef();

  useFrame((_state, delta) => {
    // helix.current.position.y += Math.sin(delta) * 0.1;
    // console.log(Math.sin(delta));
  });

  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Circle005.geometry}
        material={materials.skyblue}
        position={[0.009, 10.229, 0.676]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.781}
      />
      <mesh
        geometry={nodes.Box001001.geometry}
        material={materials.red}
        position={[0.249, 0.637, -4.55]}
        scale={0.051}
      />
      <mesh
        geometry={nodes.Plane002.geometry}
        material={materials.white}
        position={[0, 6.346, 6.757]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.946, 0.946, 0.888]}
      />
      <mesh
        geometry={nodes.Plane003.geometry}
        material={materials.black}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Circle006.geometry}
        material={materials.skyblue}
        position={[3.635, 1.147, 5.546]}
        rotation={[1.559, 0.01, -0.583]}
        scale={0.742}
      />
      <mesh
        geometry={nodes.Sphere003.geometry}
        material={materials.skyblue}
        position={[0, -2.987, 5.69]}
        scale={0.345}
      />
      <mesh
        geometry={nodes.Sphere004.geometry}
        material={materials.white}
        position={[-1.205, -2.966, 5.411]}
        scale={0.345}
      />
      <mesh
        geometry={nodes.Sphere005.geometry}
        material={materials.white}
        position={[1.312, -2.966, 5.44]}
        scale={0.345}
      />
      <mesh
        geometry={nodes.cape002.geometry}
        material={materials.yellow}
        position={[0, 4.087, -6.242]}
        scale={7.082}
      />
      <mesh
        geometry={nodes.Cube002.geometry}
        material={materials.yellow}
        position={[0, 3.681, -4.393]}
        rotation={[0.246, 0, 0]}
        scale={[7.613, 1.055, 0.376]}
      />
      <mesh
        geometry={nodes.Box004002.geometry}
        material={materials.black}
        position={[-5.972, 0.715, 1.901]}
        rotation={[-0.01, 0, 0]}
        scale={-0.051}
      />
      <mesh
        geometry={nodes.Box004003.geometry}
        material={materials.black}
        position={[5.693, 0.602, 1.901]}
        rotation={[-3.131, 0, -Math.PI]}
        scale={-0.051}
      />
      <mesh
        ref={helix}
        geometry={nodes.Box005003.geometry}
        material={materials.black}
        position={[2.018, -5.833, 0.971]}
        rotation={[-2.953, Math.PI / 2, 0]}
        scale={0.051}
      />
      <mesh
        ref={helix}
        geometry={nodes.Box005004.geometry}
        material={materials.black}
        position={[-2.833, -5.833, 0.971]}
        rotation={[-2.953, Math.PI / 2, 0]}
        scale={0.051}
      />
    </group>
  );
}

useGLTF.preload('./models/suni.glb');
